version : "3"
services:
  sample-docker:
    container_name: sample-docker
    image: sample-docker
    restart: always
    build: ./
    ports:
    - "3000:3000"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
    - /tmp/data:/data/db
    ports:
    - "27018:27017"
